fix dc check

diff --git a/bin/dc b/bin/dc
--- a/bin/dc
+++ b/bin/dc
@@ -174,6 +174,32 @@ case "$CMD" in
            docker rmi nginx:alpine ;;
   disable) docker-machine ssh $HNAME "systemctl stop docker ; systemctl disable docker" ;;
   enable)  docker-machine ssh $HNAME "systemctl enable docker ; systemctl start docker" ;;
+
+  info)    docker-machine ssh $HNAME 'echo -e "\n" ; df -h ; echo -e "\n" ; free -m ; echo -e "\n" ; uptime ; echo -e "\n"' ;;
+  check)   for i in "${!service_hosts[@]}"; do
+             if [ "${service_hosts[${i}]}" != "$HOST" ] ; then continue ; fi 
+             if [ "${service_state[${i}]}" != "active" ] ; then
+               echo "${service_state[${i}]}"
+               exit 0
+             fi
+             container_list=$(dc -c $CONF compose ps -q)
+             if [ "$container_list" = "" ] ; then
+               echo "error_no_containers"
+               exit 1
+             fi
+             stat_list=$( echo "$container_list" | xargs dc -c $CONF docker inspect --format '{{.State.Status}}')
+             for stat in $stat_list ; do
+               if [ "$stat" != "running" ] ; then
+                 echo "error_incomplete_containers"
+                 exit 1
+               fi
+             done
+             echo "Up"
+             exit 0
+           done
+           ;; 
+
+
   snap)
     SNAPDIR=/Docker/snapshot
     subcmd=$2
