Cleanup and bugfixing.

diff --git a/bin/dc b/bin/dc
--- a/bin/dc
+++ b/bin/dc
@@ -3,27 +3,27 @@
 . /etc/mde/dc/default
 
 ####################################################################################################################################
-parse_yaml() {
-    local prefix=$2
-    local s
-    local w
-    local fs
-    s='[[:space:]]*'
-    w='[a-zA-Z0-9_]*'
-    fs="$(echo @|tr @ '\034')"
-    sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
-        -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
-    awk -F"$fs" '{
-      indent = length($1)/2;
-      if (length($2) == 0) { conj[indent]="+";} else {conj[indent]="";}
-      vname[indent] = $2;
-      for (i in vname) {if (i > indent) {delete vname[i]}}
-      if (length($3) > 0) {
-              vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
-              printf("%s%s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, conj[indent-1],$3);
-      }
-    }' | sed 's/_=/+=/g'
-}
+#parse_yaml() {
+#    local prefix=$2
+#    local s
+#    local w
+#    local fs
+#    s='[[:space:]]*'
+#    w='[a-zA-Z0-9_]*'
+#    fs="$(echo @|tr @ '\034')"
+#    sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
+#        -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
+#    awk -F"$fs" '{
+#      indent = length($1)/2;
+#      if (length($2) == 0) { conj[indent]="+";} else {conj[indent]="";}
+#      vname[indent] = $2;
+#      for (i in vname) {if (i > indent) {delete vname[i]}}
+#      if (length($3) > 0) {
+#              vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
+#              printf("%s%s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, conj[indent-1],$3);
+#      }
+#    }' | sed 's/_=/+=/g'
+#}
 ####################################################################################################################################
 show_help() {
   echo ""
@@ -31,8 +31,10 @@ show_help() {
   echo ""
   echo "   options:"
   echo ""
+  echo "     -i <host-index>] ........... work with host from dc-service.yml  0|1|2|.."
   echo "     -c <path>/dc-service.yml ... work with service of the according service"
   echo "     -h <host> .................. work with this host, instead of the one which is defined in the service dc-service.yml file. "
+  echo "     -s <service> ............... work with this service."
   echo "     -v ......................... verbose"
   echo ""
   echo "   commands:"
@@ -40,10 +42,8 @@ show_help() {
   echo "     docker|compose|swarm|machine <commands>"
   echo "     create|test|remove|enable|disable|upgrade|inspect|status|ssh|info .... "
   echo "     up|rm|ps|logs [-f]|stop|start"
-  echo "     pull|push service|persistent [real]"
-  echo "     [-h <host>] services ls|check|current"
-  echo "     [-i <host-index] 0|1|2"
   echo "     -h <host> -s <service> stat ...... print service state (Up, Error, disabled,..."
+  echo "     pull|push service|persistent [real]"
   echo "     encrypt|decrypt"
   echo "     supervisor .......... connect to supervisord (help|quit|start|stop|restart)"
   echo "     login [command] ..... login or run a command within <$DCN>."
@@ -60,22 +60,6 @@ show_help() {
   echo ""
   exit 0
 }
-####################################################################################################################################
-#search_conf() {
-#  host="$1" ; service="$2"
-#
-#  find $MDE_DC_SERV_DIR/ -name dc-service.yml | while read i ; do
-#    unset service_hosts
-#    eval "$(parse_yaml $i)"
-#    for h in ${service_hosts[@]}; do
-#      if [ "$host" = "$h" -a "$service_name" = "$service" ] ; then
-#          echo "${i}"
-#          return 0
-#      fi
-#    done
-#  done
-#  return 1
-#}
 ####################################################################################################################################
 #
 # magic main
@@ -111,7 +95,6 @@ else
 fi
 
 if [ "$HOST" != "" -a "$SERVICE" != "" ] ;then
-  #CONF=$(search_conf $HOST $SERVICE)
   CONF=$(dc-list -y services -h $HOST -s $SERVICE)
   if [ "$CONF" = "" ] ; then
     echo "error: service=<$SERVICE> not defined for host=<$HOST>"
@@ -120,7 +103,8 @@ if [ "$HOST" != "" -a "$SERVICE" != "" ] ;then
 fi
 
 if [ "$CONF" != "" ] ; then
-  eval "$(parse_yaml $CONF)"
+  #eval "$(parse_yaml $CONF)"
+  eval "$(dc-yml -c $CONF)"
   HNAME=${service_hosts[${HIDX}]}
 fi
 
@@ -134,8 +118,8 @@ if [ "$CMD" = "" ] ; then
 fi  
 if [ "$HNAME" != "" ] ; then
   eval "$(docker-machine env ${HNAME})"
-  eval "$(parse_yaml ${MDE_DC_HOST_DIR}/${HNAME}/dc-host.yml)"
-  #parse_yaml $CONF
+  #eval "$(parse_yaml ${MDE_DC_HOST_DIR}/${HNAME}/dc-host.yml)"
+  eval "$(dc-yml -c ${MDE_DC_HOST_DIR}/${HNAME}/dc-host.yml)"
   SSH_KEY_FILE=${MDE_DC_HOST_DIR}/${HNAME}/${host_ssh_key}
 
   if [ "$CONF" != "" ] ; then
@@ -165,15 +149,19 @@ case "$CMD" in
   info)    docker-machine ssh $HNAME 'echo -e "\n" ; df -h ; echo -e "\n" ; free -m ; echo -e "\n" ; uptime ; echo -e "\n"' ;;
   check)   for i in "${!service_hosts[@]}"; do
              if [ "${service_hosts[${i}]}" != "$HOST" ] ; then continue ; fi 
-             #echo "$i ${service_hosts[${i}]} ${service_state[${i}]} "
              if [ "${service_state[${i}]}" != "active" ] ; then
                echo "${service_state[${i}]}"
                exit 0
              fi
-             stat_list=$( dc -c $CONF compose ps -q | xargs dc -c $CONF docker inspect --format '{{.State.Status}}')
+             container_list=$(dc -c $CONF compose ps -q)
+             if [ "$container_list" = "" ] ; then
+               echo "error_no_containers"
+               exit 1
+             fi
+             stat_list=$( echo "$container_list" | xargs dc -c $CONF docker inspect --format '{{.State.Status}}')
              for stat in $stat_list ; do
                if [ "$stat" != "running" ] ; then
-                 echo "Error"
+                 echo "error_incomplete_containers"
                  exit 1
                fi
              done
@@ -214,35 +202,6 @@ case "$CMD" in
     fi
     ;;
   #############
-  services)   if [ "$2" = "current" ] ; then
-                  unset service_hosts
-                  eval "$(parse_yaml $CONF)"
-                  echo "${service_name}"
-              else
-                find $MDE_DC_SERV_DIR/ -name dc-service.yml | while read i ; do 
-                  unset service_hosts
-                  unset service_state
-                  eval "$(parse_yaml $i)"
-                  for k in ${service_hosts[@]}; do
-                    if [ "$HOST" = "" -o "$k" = "$HOST" ] ; then  
-                      if [ "$2" = "ls" ] ; then
-                        if [ "$3" = "long" ] ; then
-                          echo "${service_name} $k ${service_state} $i" 
-                        else
-                          echo "${service_name} $k"
-                        fi
-                      elif [ "$2" = "check" ] ; then
-                        echo "###########################################################"
-                        echo "## ${service_name} ($i)"
-                        (cd `dirname $i` ; docker-compose ps  -q | xargs docker inspect --format '{{.State.Status}} : {{.Name}}')
-                      fi
-                    fi
-                    k_idx=$(( k_idx + 1))
-                  done 
-                done
-              fi
-              exit 0
-              ;;
   encrypt)    mkdir -p ./utils ; tar -cjv ./private | openssl aes-256-cbc -salt -out ./utils/.private.enc ; rm -Rvf ./private ;;
   decrypt)    openssl aes-256-cbc -d -salt -in ./utils/.private.enc | tar xjv ;;
   ############
@@ -292,6 +251,4 @@ case "$CMD" in
                 docker-machine $*
               fi
               ;;
-  
-   
 esac
