Re-work on dc-config and hcloud implementation.

diff --git a/bin/dc-config b/bin/dc-config
--- a/bin/dc-config
+++ b/bin/dc-config
@@ -2,11 +2,19 @@
 
 . /opt/dc/funcs/global
 
+
+call_from="$(ps -o comm= $PPID)"
+if [ "$call_from" == "dc" ] ; then
+  IAM="dc config"
+else
+  IAM="dc-config"
+fi
+
 VARDIR="/opt/dc/var/cache"
 
 project_dir="$VARDIR/projects"
 hosts_dir="$VARDIR/hosts"
-
+############################################################################################################################################
 _config_refresh()
 {
   config_change="0"
@@ -75,8 +83,6 @@ _config_refresh()
     fi
   done
 
-
-
   if [ "$config_change" = "1" ] ; then
     mkdir -p `dirname ${MDE_DC_YAML}`
     echo "re-create: ${MDE_DC_YAML}"
@@ -103,71 +109,196 @@ _config_refresh()
   fi
 }
 
+############################################################################################################################################
+# magic main
+############################################################################################################################################
 if [ "$1" = "" ] ; then
   echo ""
-  echo "usage: $IAM check"
-  echo "usage: $IAM create project <host> <project-name> <main-service-name> <project-directory>"
+  echo "usage: $IAM ..."
   echo ""
-  echo "examples:"
+  echo "# common config commands:"
   echo ""
-  echo "$IAM show     # show dc configuration"
-  echo "$IAM refresh  # refresh dc config environment (${MDE_DC_YAML})"
-  echo "$IAM rebuild  # rebuild dc config environment (${MDE_DC_YAML})"
-  echo "$IAM create project apps0 test-project filebrowser ${MDE_DC_SERV_DIR}/test-project"
+  echo "$IAM show         # show dc configuration"
+  echo "$IAM refresh      # refresh dc config environment (${MDE_DC_YAML})"
+  echo "$IAM rebuild      # rebuild dc config environment (${MDE_DC_YAML})"
+  echo ""
+  echo "# create/delete a sample project:"
+  echo "" 
+  echo "#$IAM create project <name>       <host> <main_service> <project_dir>"
+  echo "$IAM  create project test-project apps0  filebrowser ${MDE_DC_SERV_DIR}/test-project"
+  echo "$IAM  delete project test-project"
+  echo ""
+  echo "# create/delete a host definition"
+  echo ""
+  echo "#$IAM create host    <host>     [<hostname_or_ip]"
+  echo "$IAM  create host    test-host  localhost"
+  echo "$IAM  delete host    test-host"
   echo ""
   exit 0
 fi
 
-if [ "$1" = "rebuild" ] ; then
+CMD="$1"
+shift
+
+######################################################################################################################
+if [ "$CMD" = "rebuild" ] ; then
   rm -rf $VARDIR
   _config_refresh
   exit $?
 fi
 
-if [ "$1" = "refresh" ] ; then
+######################################################################################################################
+if [ "$CMD" = "refresh" ] ; then
    _config_refresh
   exit $?
 fi
 
-if [ "$1" = "create" -a "$2" = "project" ] ; then
-  shift ; shift
-  host="$1"
-  project_name="$2"    # must be unique
-  main_service="$3"    # keep it simple, like git,...
-  project_dir="$4"
-
-  traefik_net="traefik_default"
-  image="filebrowser/filebrowser:v2.25.0"
-
-  if [ -d ${project_dir} ] ; then
-    echo "error: ${project_dir} exists!"
-    exit 1
+######################################################################################################################
+if [ "$CMD" = "create" -o "$CMD" = "delete" ] ; then
+  TYP="$1"
+  shift
+  if [ "$TYP" = "project" ] ; then
+    project_name="$1"    # must be unique
+    project_dir=$( dc-yq '.projects.'$project_name'.project_dir'  ${MDE_DC_YAML} )
+    if [ "$CMD" = "delete" ] ; then
+      echo "################################################################################"
+      echo "# delete project <$project_name> definition"
+      echo "################################################################################"
+      if [ "$project_dir" = "null" ] ; then
+        echo "error: project <$project_name> did not exist!"
+        exit 1
+      fi
+      project_hosts=$( dc-yq '.projects.'$project_name'.dc.home.[].host' ${MDE_DC_YAML} )
+      for i in $project_hosts ; do
+        nrc=$(dc-host -p $project_name -h $i $host nrc)
+        found=0
+        if [ "$nrc" != "0" ] ; then
+          echo " $nrc containers still running on <$i> for this project"
+          found=1
+        fi
+      done
+      if [ "$found" = "1" ] ; then
+        echo "error: do: dc -p ..."
+        exit 1
+      fi
+      echo "TBD: check volumes of project on target host"
+      rm -rvf $project_dir
+      exit 0
+    elif [ "$CMD" = "create" ] ; then
+      echo "################################################################################"
+      echo "# create project <$project_name>"
+      echo "################################################################################"
+      host="$2"
+      if [ "$(dc-yq '.hosts.'$host'.state' ${MDE_DC_YAML})" = "null" ] ; then
+        echo "error: host <$host> did not exist!"
+        exit 1
+      fi
+      if [ "$project_dir" != "null" ] ;then
+        echo "error: project <$project_name> already exists exists!"     
+        exit 1
+      fi
+      main_service="$3"    # keep it simple, like: git,...
+      conf_dir="$4"
+      traefik_net="traefik_default"
+      image="filebrowser/filebrowser:v2.25.0"
+      if [ -d ${conf_dir} ] ; then
+        echo "error: ${conf_dir} exists!"
+        exit 1
+      fi
+      mkdir -p ${conf_dir}
+      echo "${conf_dir} created"
+      cp -r /opt/dc/templates/create/project/.   ${conf_dir}/
+      flist=$( find  ${conf_dir} -type f)
+      for i in $flist ; do
+        sed -i "s|<project_name>|${project_name}|g"   $i
+        sed -i "s|<main_service>|${main_service}|g"   $i
+        sed -i "s|<host>|${host}|g"                   $i
+        sed -i "s|<image>|${image}|g"                 $i
+        sed -i "s|<traefik_net>|${traefik_net}|g"     $i
+        echo "$i"
+      done
+      cd ${conf_dir}
+      dc config refresh
+      dc up
+      dc login ls /
+      dc rm
+      exit 0
+    fi
   fi
-  mkdir -p ${project_dir}
-  echo "${project_dir} created"
-  cp -r /opt/dc/templates/create-project/.         ${project_dir}/
-  flist=$( find  ${project_dir} -type f)
-  for i in $flist ; do
-    sed -i "s|<project_name>|${project_name}|g"   $i
-    sed -i "s|<main_service>|${main_service}|g"   $i
-    sed -i "s|<host>|${host}|g"                   $i
-    sed -i "s|<image>|${image}|g"                 $i
-    sed -i "s|<traefik_net>|${traefik_net}|g"     $i
-    echo "$i"
-  done
-  cd ${project_dir}
-  dc config refresh
-  dc up
-  dc login ls /
-  dc rm
-  exit 0
+  if [ "$TYP" = "host" ] ; then
+    name="$1"
+    if [ "$name" = "" ] ; then
+      echo "error: invalid host name <$name> given!"
+      exit 1
+    fi
+    exists=$( dc-yq '.hosts.'$name'.state' ${MDE_DC_YAML} )
+    if [ "$CMD" = "delete" ] ; then
+      echo "################################################################################"
+      echo "# delete host <$name> definition"
+      echo "################################################################################"
+      if [ "$exists" = "null" ] ; then
+         echo "error: host <$name> did not exist!"
+         exit 1
+      fi
+      if [ "$( dc-list projects -h $name)" != "" ] ; then
+        echo "error: the following projects still defined for host <$name> :"
+        dc-list projects -h $name | sed "s|^| - |g" 
+        exit 1
+      fi
+      echo "TBD in $0 : do not allow, if hcloud server is assigned an running!"
+      rm -fv ${MDE_DC_DIR}/.ssh/dc/config/${name}.*
+      exit 0
+    fi
+    if [ "$CMD" = "create" ] ; then
+      echo "################################################################################"
+      echo "# create host <${name}> definition"
+      echo "################################################################################"
+      if [ -f "${MDE_DC_DIR}/.ssh/dc/config/${name}.yml" ] ; then
+        echo "error: <${MDE_DC_DIR}/.ssh/dc/config/${name}.yml> exists!"
+        echo "remove it with:  rm -vf ${MDE_DC_DIR}/.ssh/dc/config/${name}.*" 
+        exit 1
+      fi
+      cp  /opt/dc/templates/create/host/host.config ${MDE_DC_DIR}/.ssh/dc/config/${name}.ssh
+      cp  /opt/dc/templates/create/host/host.yml    ${MDE_DC_DIR}/.ssh/dc/config/${name}.yml
+      flist="${MDE_DC_DIR}/.ssh/dc/config/${name}.ssh ${MDE_DC_DIR}/.ssh/dc/config/${name}.yml"
+      hostname="$name"
+      if [ "$2" != "" ] ; then
+        hostname="$2"
+      fi
+      for i in $flist ; do
+          sed -i "s|<name>|${name}|g"   $i
+          sed -i "s|<hostname_or_ip>|${hostname}|g"   $i
+          echo "created '$i'"
+      done   
+    fi
+    exit 0
+  fi
 fi
 
-if [ "$1" = "show"  ] ; then
+if [ "$CMD" = "yq" -o  "$CMD" = "edit"  ] ; then
+  if [[ "$1" == "" || ( "$1" != "host" &&  "$1" != "project" ) ]] ; then
+    echo "error: unkown type given. Use host or project!"
+    exit 1
+  fi
+  TYP="$1" ; shift
+  if [ "$1" == "" ] ; then
+    echo "error: no $TYP name given!"
+    exit 1
+  fi
+  name="$1" ; shift
+  rest=$*
+  #if [ "$TYP" = "host" ] ; then
+  #else
+  #fi
+  echo "conig_file="
+  exit $?  
+fi
+
+if [ "$CMD" = "show"  ] ; then
   dc-yq ${MDE_DC_YAML}
 fi  
 
-if [ "$1" = "check" ] ; then
+if [ "$CMD" = "check" ] ; then
   echo " ✅ last modification of ${MDE_DC_YAML} <$(date -r ${MDE_DC_YAML} "+%Y-%m-%d %H:%M:%S")>"
   hosts=$( dc-yq  '.projects.*.dc.home.[].host'   ${MDE_DC_YAML}  | sort | uniq)
   for h in $hosts ; do
@@ -188,7 +319,6 @@ if [ "$1" = "check" ] ; then
     #
     # check for not unique project names
     #
-    
     anz=$( dc-yq '.projects' ${MDE_DC_YAML} | grep "^${p}:"  | wc -l)
     if [ "$anz" != "1" ] ; then
       echo " ❌ project name [$p] not unique"
diff --git a/bin/dc-server b/bin/dc-server
--- a/bin/dc-server
+++ b/bin/dc-server
@@ -1,34 +1,139 @@
 #!/bin/bash
 
-hname="tescht"
+. /opt/dc/funcs/global
 
-
-if [ "$1" = "create" ] ; then
-  hcloud server create --name ${hname}  --type cx11 --image ubuntu-22.04 --ssh-key dc-pub-key --location fsn1
-  sleep 20
-  IP=$(hcloud server ip ${hname})
-  ssh-keygen -f "/root/.ssh/known_hosts" -R ${IP} 
-  scp -o StrictHostKeychecking=no /opt/dc/helper/docker@ubuntu-22.04.sh ${IP}:/tmp/dc-install
-  ssh -o StrictHostKeychecking=no ${IP} /tmp/dc-install
-  ssh -o StrictHostKeychecking=no ${IP} init 6
-  # todo set root password
+if [ "$1" = "" ] ; then
+  echo ""
+  echo "TBD"
+  exit 0
 fi
 
-if [ "$1" = "info" ] ; then
+CMD="$1"
+shift
+
+dc_host="$1"
+
+if [ "$CMD" = "reboot" ] ; then
+  ssh ${dc_host} "init 6"
+  echo "#########################################"
+  echo "# reboot host <${dc_host}> and wait until server is up"
+  echo "#########################################"
+  sleep 3
+  while true ; do
+    state=$( dc host -h ${dc_host} state )
+    echo "wait for state==dock current-state=state=$state"
+    if [ "$state" = "dock" ] ; then
+      break
+    fi
+    sleep 1
+  done
+  exit 0
+fi
+
+if [ "$CMD" = "install" ] ; then
+  echo "################################################################################"
+  echo "# install docker, set timezone, dist-upgrade on host <$dc_host>"
+  echo "################################################################################"
+  image=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.image'     ${MDE_DC_YAML} )
+  if [ ! -f /opt/dc/helper/hcloud-${image}.sh ] ; then
+    echo "error: missing installation script </opt/dc/helper/hcloud-${image}.sh>"
+    exit 1
+  fi
+  scp /opt/dc/helper/hcloud-${image}.sh ${dc_host}:/tmp/dc-install
+  ssh ${dc_host} /tmp/dc-install >/dev/null
+  exit $?
+fi
+
+if [ "$CMD" = "assign" ] ; then
+  shift
+  echo "################################################################################"
+  echo "# assing hcloud options to host <${dc_host}> definition"
+  echo "################################################################################"
+  if [ "$1" != "hcloud" ] ; then
+    echo "error unsupported server provider <$1> given!"
+    exit 1
+  fi
+  shift
+  FI=/root/.ssh/dc/config/${dc_host}.yml
+  for i in $* ; do
+    key=${i%=*}
+    val=${i#*=}
+    echo "$i   <$key> <$val>"
+    dc-yq -i '.host.server.hcloud.'$key' = "'${val}'"'         $FI
+  done
+  dc config refresh
+  dc-yq '.hosts.'${dc_host}'.server' ${MDE_DC_YAML}
+  exit 0
+fi
+
+hname=$(dc-yq '.hosts.'${dc_host}'.server.hcloud.name' ${MDE_DC_YAML} )
+if [ "$hname" = "" -o "$hname" = "null" ] ; then
+  echo "error: missing hcloud server name in <.hosts.${1}.server.hcloud.name>"
+  exit 1
+fi
+
+if [ "$CMD" = "create" ] ; then
+  echo "################################################################################"
+  echo "# create vserver based on host definition in ${MDE_DC_YAML}"
+  echo "################################################################################"
+  
+  typ=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.type'     ${MDE_DC_YAML} )
+  img=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.image'    ${MDE_DC_YAML} )
+  loc=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.location' ${MDE_DC_YAML} )
+  key=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.ssh-key'  ${MDE_DC_YAML} )
+  echo server create --name ${hname} --type $typ --image $img --location $loc --ssh-key $key
+  hcloud server create --name ${hname} --type $typ --image $img --location $loc --ssh-key $key
+  IP=$(hcloud server ip ${hname} )  
+  echo "################################################################################"
+  echo "# assign vserver HostName <$IP> to host <${dc_host}> definition"
+  echo "################################################################################"
+  ssh-keygen -f "/root/.ssh/known_hosts" -R ${IP} >/dev/null 2>&1
+  rm -f /root/.ssh/dc/control/${dc_host}
+  dc-yq -i '.host.hostname = "'${IP}'"'   /root/.ssh/dc/config/${dc_host}.yml
+  sed -i "s|HostName .*|HostName ${IP}|g" /root/.ssh/dc/config/${dc_host}.ssh
+  dc config refresh
+  dc-yq '.hosts.'${dc_host} ${MDE_DC_YAML}
+  cat /root/.ssh/dc/config/${dc_host}.ssh
+  echo "###########################################"
+  echo "# wait until new sever is reachable via ssh"
+  echo "###########################################"
+  while true ; do
+    state=$( dc host -h ${dc_host} state )
+    echo "wait for state==sshd current-state=state=$state"
+    if [ "$state" = "sshd" ] ; then
+      break
+    fi
+    sleep 1
+  done
+  exit 0
+fi
+
+if [ "$CMD" = "info" ] ; then
   hcloud server describe ${hname}
 fi
 
-if [ "$1" = "list" ] ; then
-  hcloud server list
+if [ "$CMD" = "list" ] ; then
+  #hcloud server list
   #hcloud image list
   #hcloud location list
   #hcloud server-type list
+  exit 0
 fi
 
-
-
-if [ "$1" = "delete" ] ; then
-  hcloud server delete ${hname}
+if [ "$CMD" = "delete" ] ; then
+  echo "################################################################################"
+  echo "# delete Hetzner cloud server <$hname>"
+  echo "################################################################################"
+  # check if projects are defined for the host then error and exit
+  project_list=$( dc-list projects -h ${dc_host}  )
+  if [ "$project_list" != "" ] ; then
+    echo "projects assigned to <${dc_host}>:"
+    dc-list projects -h ${dc_host} | sed "s|^|  - |g"
+    echo "error: unable to delete server <$hname>"
+    exit 1
+  fi
+  hcloud server delete $hname
+  exit $?
 fi
 
 
