fix dc-check

diff --git a/bin/dc-check b/bin/dc-check
--- a/bin/dc-check
+++ b/bin/dc-check
@@ -3,7 +3,8 @@
 . /opt/dc/etc/config
 . /opt/dc/funcs/script_funcs
 
-sf_start
+error=0
+error_list=""
 
 if [ "$1" = "" ] ; then
   echo ""
@@ -19,7 +20,9 @@ else
 fi
 
 for host in $hosts ; do
+  echo "#"	
   echo "# checking host $host ..."
+  echo "#"
   host_error_marker=0
   H_STATE=$( dc-yml -c $MDE_DC_HOST_DIR/$host/dc-host.yml host_state )
   if [ "$H_STATE" = "active" ] ; then
@@ -29,7 +32,8 @@ for host in $hosts ; do
     else
       host_up=0
       host_error_marker=1
-      sf_set_error
+      error_list="$error_list $host:not_running"
+      error=1
     fi
   else
     state=$H_STATE
@@ -54,7 +58,8 @@ for host in $hosts ; do
       service_stat=$( dc -h $host -s $service check )
       if [ "$?" != "0" ] ; then
         host_error_marker=1
-        sf_set_error
+	error_list="$error_list $host:$service"
+        error=1
       fi
       echo "$host.service.$service.state=$service_stat"
     else
@@ -81,5 +86,10 @@ for host in $hosts ; do
   fi
 
 done
-sf_end
+if [ "$error" = "1" ] ; then
+  echo "#"	
+  echo "# detected errors: $error_list"
+  echo "#"	
+fi
+exit $error
 
