Rename dc-server to dc-vserver

diff --git a/bin/dc-config b/bin/dc-config
--- a/bin/dc-config
+++ b/bin/dc-config
@@ -37,18 +37,20 @@ _config_refresh()
   #
   # check for changed hosts configurations
   #
-  last=$( find /root/.ssh/dc/config  -maxdepth 1 -name "*.yml" -printf "%TF_%TT %p\n" | awk '{if ($0>max) max = $0} END{print max}'   )
+  last=$( find ${MDE_DC_HOST_DIR} -maxdepth 2 -name "host.yml" -printf "%TF_%TT %p\n" | awk '{if ($0>max) max = $0} END{print max}'   )
   stamp=${last% *}
   if [ ! -f ${hosts_dir}/modified.${stamp} ] ; then
     rm -rf ${hosts_dir}
     mkdir ${hosts_dir}
     echo "$last" | awk '{ print $2 }' > ${hosts_dir}/modified.${stamp}
-    list=$( find /root/.ssh/dc/config -name "*.yml" )
-    echo "hosts:" > ${hosts_dir}/hosts.yml
+    list=$( find ${MDE_DC_HOST_DIR}  -name "*.yml" )
+    echo "hosts:"                                               > ${hosts_dir}/hosts.yml
     for i in $list ; do
-      name=`basename $i`
-      name=${name%.yml}
-      sed "s|^host:|${name}:|g" $i | sed "s|^|  |g" | grep -o '^[^#]*' | sed '/^[[:space:]]*$/d' >> ${hosts_dir}/hosts.yml
+      name=${i#${MDE_DC_HOST_DIR}/}
+      name=${name%/host.yml}
+      echo "  $name:"                                           >> ${hosts_dir}/hosts.yml
+      echo "    host_dir: ${MDE_DC_HOST_DIR}/$name"             >> ${hosts_dir}/hosts.yml
+      sed "s|^host:||g" $i | sed "s|^|  |g" | grep -o '^[^#]*' | sed '/^[[:space:]]*$/d' >> ${hosts_dir}/hosts.yml
     done
     config_change="1"
   fi
@@ -194,7 +196,7 @@ if [ "$CMD" = "create" -o "$CMD" = "delete" ] ; then
         exit 1
       fi
       if [ "$project_dir" != "null" ] ;then
-        echo "error: project <$project_name> already exists exists!"     
+        echo "error: project <$project_name> already exists!"     
         exit 1
       fi
       main_service="$3"    # keep it simple, like: git,...
@@ -231,12 +233,12 @@ if [ "$CMD" = "create" -o "$CMD" = "delete" ] ; then
       echo "error: invalid host name <$name> given!"
       exit 1
     fi
-    exists=$( dc-yq '.hosts.'$name'.state' ${MDE_DC_YAML} )
+    host_dir=$( dc-yq '.hosts.'$name'.host_dir' ${MDE_DC_YAML} )
     if [ "$CMD" = "delete" ] ; then
       echo "################################################################################"
       echo "# delete host <$name> definition"
       echo "################################################################################"
-      if [ "$exists" = "null" ] ; then
+      if [ "$host_dir" = "null" ] ; then
          echo "error: host <$name> did not exist!"
          exit 1
       fi
@@ -246,27 +248,31 @@ if [ "$CMD" = "create" -o "$CMD" = "delete" ] ; then
         exit 1
       fi
       echo "TBD in $0 : do not allow, if hcloud server is assigned an running!"
-      rm -fv ${MDE_DC_DIR}/.ssh/dc/config/${name}.*
+      rm -rv ${MDE_DC_HOST_DIR}/$name
       exit 0
     fi
     if [ "$CMD" = "create" ] ; then
       echo "################################################################################"
       echo "# create host <${name}> definition"
       echo "################################################################################"
-      if [ -f "${MDE_DC_DIR}/.ssh/dc/config/${name}.yml" ] ; then
-        echo "error: <${MDE_DC_DIR}/.ssh/dc/config/${name}.yml> exists!"
-        echo "remove it with:  rm -vf ${MDE_DC_DIR}/.ssh/dc/config/${name}.*" 
+      if [  "$host_dir" != "null"  ] ; then
+        echo "error: host <$name> already exist!"
         exit 1
       fi
-      cp  /opt/dc/templates/create/host/host.config ${MDE_DC_DIR}/.ssh/dc/config/${name}.ssh
-      cp  /opt/dc/templates/create/host/host.yml    ${MDE_DC_DIR}/.ssh/dc/config/${name}.yml
-      flist="${MDE_DC_DIR}/.ssh/dc/config/${name}.ssh ${MDE_DC_DIR}/.ssh/dc/config/${name}.yml"
+      if [ -d ${MDE_DC_HOST_DIR}/$name ] ; then
+        echo "error: <${MDE_DC_HOST_DIR}/$name exists!"
+        echo "remove it with:  rm -rf ${MDE_DC_HOST_DIR}/$name" 
+        exit 1
+      fi
       hostname="$name"
       if [ "$2" != "" ] ; then
         hostname="$2"
       fi
+      mkdir -p ${MDE_DC_HOST_DIR}/$name
+      cp  /opt/dc/templates/create/host/*     ${MDE_DC_HOST_DIR}/$name
+      flist=$(find ${MDE_DC_HOST_DIR}/$name -type f)
       for i in $flist ; do
-          sed -i "s|<name>|${name}|g"   $i
+          sed -i "s|<name>|${name}|g"                 $i
           sed -i "s|<hostname_or_ip>|${hostname}|g"   $i
           echo "created '$i'"
       done   
@@ -286,11 +292,25 @@ if [ "$CMD" = "yq" -o  "$CMD" = "edit"  ] ; then
     exit 1
   fi
   name="$1" ; shift
-  rest=$*
-  #if [ "$TYP" = "host" ] ; then
-  #else
-  #fi
-  echo "conig_file="
+  rest=$@
+  if [ "$TYP" = "host" ] ; then
+    config_dir=$( dc-yq '.hosts.'$name'.host_dir' ${MDE_DC_YAML}  )
+    file="host.yml"
+  else
+    config_dir=$( dc-yq '.projects.'$name'.project_dir' ${MDE_DC_YAML}  )
+    file="docker-compose.yml"
+  fi
+  if [ "$config_dir" = "null" ] ; then
+    echo "error: $TYP <$name> does not exists!"
+    exit 1
+  fi 
+  if [ "$CMD" = "edit" ] ; then
+    vi $config_dir
+  else
+    echo "<$1> <$2>"
+    x="'"$2"'" 
+    echo dc-yq $x $config_dir/$file
+  fi
   exit $?  
 fi
 
diff --git a/bin/dc-vserver b/bin/dc-vserver
--- a/bin/dc-vserver
+++ b/bin/dc-vserver
@@ -12,7 +12,9 @@ CMD="$1"
 shift
 
 dc_host="$1"
-
+###################################################################
+# reboot
+###################################################################
 if [ "$CMD" = "reboot" ] ; then
   ssh ${dc_host} "init 6"
   echo "#########################################"
@@ -30,20 +32,42 @@ if [ "$CMD" = "reboot" ] ; then
   exit 0
 fi
 
+###################################################################
+# install
+###################################################################
 if [ "$CMD" = "install" ] ; then
   echo "################################################################################"
   echo "# install docker, set timezone, dist-upgrade on host <$dc_host>"
   echo "################################################################################"
-  image=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.image'     ${MDE_DC_YAML} )
+  image=$( dc-yq '.hosts.'${dc_host}'.vserver.hcoud.init.image'     ${MDE_DC_YAML} )
   if [ ! -f /opt/dc/helper/hcloud-${image}.sh ] ; then
     echo "error: missing installation script </opt/dc/helper/hcloud-${image}.sh>"
     exit 1
   fi
   scp /opt/dc/helper/hcloud-${image}.sh ${dc_host}:/tmp/dc-install
   ssh ${dc_host} /tmp/dc-install >/dev/null
-  exit $?
+  echo "TBD: Disable PasswordAuthentication in sshd_config ..."
+  #ssh  ${dc_host} "sed -i  's|#PasswordAuthentication yes|PasswordAuthentication no|g' /etc/ssh/sshd_config" 
+  echo "TBD: Unset root password ..."
+  #ssh  ${dc_host}"usermod -p ! root"
+  ret=$?
+  exit $ret
 fi
 
+###################################################################
+# list 
+###################################################################
+if [ "$CMD" = "list" ] ; then
+  hcloud server list
+  #hcloud image list
+  #hcloud location list
+  #hcloud server-type list
+  exit 0
+fi
+
+###################################################################
+# assign
+###################################################################
 if [ "$CMD" = "assign" ] ; then
   shift
   echo "################################################################################"
@@ -54,33 +78,38 @@ if [ "$CMD" = "assign" ] ; then
     exit 1
   fi
   shift
-  FI=/root/.ssh/dc/config/${dc_host}.yml
+  host_dir=$( dc-yq '.hosts.'${dc_host}'.host_dir' ${MDE_DC_YAML} )
   for i in $* ; do
     key=${i%=*}
     val=${i#*=}
-    echo "$i   <$key> <$val>"
-    dc-yq -i '.host.server.hcloud.'$key' = "'${val}'"'         $FI
+    #echo "$i   <$key> <$val>"
+    dc-yq -i '.host.vserver.hcoud.'$key' = "'${val}'"'   $host_dir/host.yml
   done
   dc config refresh
-  dc-yq '.hosts.'${dc_host}'.server' ${MDE_DC_YAML}
+  dc-yq '.hosts.'${dc_host}'.vserver' ${MDE_DC_YAML}
   exit 0
 fi
 
-hname=$(dc-yq '.hosts.'${dc_host}'.server.hcloud.name' ${MDE_DC_YAML} )
+hname=$(dc-yq '.hosts.'${dc_host}'.vserver.hcoud.name' ${MDE_DC_YAML} )
 if [ "$hname" = "" -o "$hname" = "null" ] ; then
-  echo "error: missing hcloud server name in <.hosts.${1}.server.hcloud.name>"
+  echo "error: missing hcloud server name in <.hosts.${1}.vserver.hcoud.name>"
   exit 1
 fi
 
+###################################################################
+# create
+###################################################################
 if [ "$CMD" = "create" ] ; then
   echo "################################################################################"
   echo "# create vserver based on host definition in ${MDE_DC_YAML}"
   echo "################################################################################"
   
-  typ=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.type'     ${MDE_DC_YAML} )
-  img=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.image'    ${MDE_DC_YAML} )
-  loc=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.location' ${MDE_DC_YAML} )
-  key=$( dc-yq '.hosts.'${dc_host}'.server.hcloud.init.ssh-key'  ${MDE_DC_YAML} )
+  host_dir=$( dc-yq '.hosts.'${dc_host}'.host_dir' ${MDE_DC_YAML} )
+  
+  typ=$( dc-yq '.hosts.'${dc_host}'.vserver.hcoud.init.type'     ${MDE_DC_YAML} )
+  img=$( dc-yq '.hosts.'${dc_host}'.vserver.hcoud.init.image'    ${MDE_DC_YAML} )
+  loc=$( dc-yq '.hosts.'${dc_host}'.vserver.hcoud.init.location' ${MDE_DC_YAML} )
+  key=$( dc-yq '.hosts.'${dc_host}'.vserver.hcoud.init.ssh-key'  ${MDE_DC_YAML} )
   echo server create --name ${hname} --type $typ --image $img --location $loc --ssh-key $key
   hcloud server create --name ${hname} --type $typ --image $img --location $loc --ssh-key $key
   IP=$(hcloud server ip ${hname} )  
@@ -88,12 +117,13 @@ if [ "$CMD" = "create" ] ; then
   echo "# assign vserver HostName <$IP> to host <${dc_host}> definition"
   echo "################################################################################"
   ssh-keygen -f "/root/.ssh/known_hosts" -R ${IP} >/dev/null 2>&1
-  rm -f /root/.ssh/dc/control/${dc_host}
-  dc-yq -i '.host.hostname = "'${IP}'"'   /root/.ssh/dc/config/${dc_host}.yml
-  sed -i "s|HostName .*|HostName ${IP}|g" /root/.ssh/dc/config/${dc_host}.ssh
+  ssh-keyscan -H ${IP} >> /root/.ssh/known_hosts
+  rm -f ${MDE_DC_HOST_DIR}/.control/${dc_host}
+  dc-yq -i '.host.hostname = "'${IP}'"'   $host_dir/host.yml
+  sed -i "s|HostName .*|HostName ${IP}|g" $host_dir/host.ssh
   dc config refresh
   dc-yq '.hosts.'${dc_host} ${MDE_DC_YAML}
-  cat /root/.ssh/dc/config/${dc_host}.ssh
+  cat $host_dir/host.yml
   echo "###########################################"
   echo "# wait until new sever is reachable via ssh"
   echo "###########################################"
@@ -108,18 +138,16 @@ if [ "$CMD" = "create" ] ; then
   exit 0
 fi
 
+###################################################################
+# info
+###################################################################
 if [ "$CMD" = "info" ] ; then
   hcloud server describe ${hname}
 fi
 
-if [ "$CMD" = "list" ] ; then
-  #hcloud server list
-  #hcloud image list
-  #hcloud location list
-  #hcloud server-type list
-  exit 0
-fi
-
+###################################################################
+# delete
+###################################################################
 if [ "$CMD" = "delete" ] ; then
   echo "################################################################################"
   echo "# delete Hetzner cloud server <$hname>"
