Introduce yml cache.

diff --git a/bin/dc-config b/bin/dc-config
--- a/bin/dc-config
+++ b/bin/dc-config
@@ -2,12 +2,15 @@
 
 . /opt/dc/etc/config
 
+if [ $(ps -o comm= $PPID) = "dc" ] ; then
+  IAM="dc config"
+else
+  IAM="dc-config"
+  echo "cache refresh in $IAM"
+  dc-yml-cache refresh
+fi
+
 if [ "$1" = "" ] ; then
-  if [ $(ps -o comm= $PPID) = "dc" ] ; then
-    IAM="dc config"
-  else
-    IAM="dc-config"
-  fi
   echo ""
   echo "usage: $IAM check"
   echo "usage: $IAM create project <host> <project-name> <main-service-name> <project-directory>"
@@ -54,63 +57,61 @@ if [ "$1" = "create" -a "$2" = "project" ] ; then
   exit 0
 fi
 
+if [ "$1" = "show"  ] ; then
+  cat /var/dc/dc.yml
+fi  
 
-
-
-if [ "$1" = "check" -o "show"  ] ; then
-  flist=$( find $MDE_DC_SERV_DIR/ -name dc-service.yml )
-
-  cname_list=" "
-
-  for i in $flist ; do
-    config_check=$( dc-yq '.service.config_check' $i )
-    c_yaml=$( dc-yq '.service.control.file' $i )
-    if [ "${c_yaml}" = "" ] ; then
-      echo " ❌ fehler 1"
-      exit 1
+if [ "$1" = "check" ] ; then
+  hosts=$(yq  '.*.dc.hosts.[]'   /var/dc/dc.yml | sort | uniq)
+  for h in $host ; do
+    if [ ! -f /root/.ssh/dc/config.$h ] ; then
+      echo " ❌ missing host definition </root/.ssh/dc/config.$h>"
     fi
-    c_yaml="`dirname $i`/${c_yaml}"
-    cname=$(docker compose -f ${c_yaml} config |  dc-yq '.name')
-    if [[ "$cname_list" == *" $cname "* ]] ; then
+  done
+
+  projects=$(dc-yq  '.* | path | .[-1]' /var/dc/dc.yml | sort)
+  doubles=" "
+  for p in $projects ; do
+    config_check=$( dc-yq '.'$p'.dc.config_check' /var/dc/dc.yml )
+    p_on_hosts=$( dc-yq '.'$p'.dc.hosts.[]' /var/dc/dc.yml )
+    #echo "$p $config_check ($p_on_hosts)"
+    #
+    # check for not unique projects
+    #
+    if [[ "$doubles" == *" $p "* ]] ; then
       if [ "$config_check" != "false" ] ; then
-        echo " 💡(2) not-uniqu:  $cname   ($i)"
+        echo " 💡(1) not-uniqu:  $p"
       fi
+    else
+      doubles="$doubles $p"
     fi
-    cname_list="$cname_list $cname "    
-    hosts=$( dc-yq '.service.hosts.[]' $i )
-    if [ "$config_check" != "false" ] ; then
-      vol_list=$(docker compose -f ${c_yaml} config | dc-yq '.services.*.volumes.[].source' | grep -v "^/etc/"  | grep -v "^/var/" | grep -v "^/lib/")
-      for vol in $vol_list ; do
-        if [ "$1" = "show" ] ; then
-          echo "volume: $vol"
-        fi
-        if [[ "$vol" == "${MDE_DC_DOCKER_VOL}/Logs/$cname"         || \
-              "$vol" == "${MDE_DC_DOCKER_VOL}/Logs/$cname/"*       || \
-              "$vol" == "${MDE_DC_DOCKER_VOL}/Services/$cname"     || \
-              "$vol" == "${MDE_DC_DOCKER_VOL}/Services/$cname/"*   || \
-              "$vol" == "${MDE_DC_DOCKER_VOL}/Cache/$cname"        || \
-              "$vol" == "${MDE_DC_DOCKER_VOL}/Cache/$cname/"*      || \
-              "$vol" == "${MDE_DC_DOCKER_VOL}/Data/$cname"         || \
-              "$vol" == "${MDE_DC_DOCKER_VOL}/Data/$cname/"*          \
-           ]] ; then
-          #echo "check if $vol exists on host"
-          for h in $hosts ; do
-            ssh $h ls -d $vol >/dev/null 2>&1
-            if [ "$?" != "0" ] ; then
-              echo " ❌ missing volume directory <$vol> on host <$h> ($i)"
-            fi
-          done
-        else 
-          echo " 💡(3) volconfig:  $vol ($cname)"
-        fi
-      done
-    fi
-    for h in $hosts ; do
-      if [ ! -f /root/.ssh/dc/config.$h ] ; then
-        echo " ❌ missing host definition </root/.ssh/dc/config.$h>"
+    vol_list=$(dc-yq '.'$p'.compose.services.*.volumes.[].source' /var/dc/dc.yml | grep -v "^/etc/"  | grep -v "^/var/" | grep -v "^/lib/"  )
+    for vol in $vol_list ; do
+      if [ "$config_check" = "false" ] ; then
+        continue
+      fi
+      #echo "  $vol" 
+      if [[ "$vol" == "${MDE_DC_DOCKER_VOL}/Logs/$p"         || \
+            "$vol" == "${MDE_DC_DOCKER_VOL}/Logs/$p/"*       || \
+            "$vol" == "${MDE_DC_DOCKER_VOL}/Services/$p"     || \
+            "$vol" == "${MDE_DC_DOCKER_VOL}/Services/$p/"*   || \
+            "$vol" == "${MDE_DC_DOCKER_VOL}/Cache/$p"        || \
+            "$vol" == "${MDE_DC_DOCKER_VOL}/Cache/$p/"*      || \
+            "$vol" == "${MDE_DC_DOCKER_VOL}/Data/$p"         || \
+            "$vol" == "${MDE_DC_DOCKER_VOL}/Data/$p/"*          \
+         ]] ; then
+        #echo "check if $vol exists on host"
+        for h in $p_on_hosts ; do
+          ssh $h ls -d $vol >/dev/null 2>&1
+          if [ "$?" != "0" ] ; then
+            echo " ❌ missing volume directory <$vol> on host <$h>"
+          fi
+        done
+      else
+        echo " 💡(2) volconfig:  $vol"
       fi
     done
   done
-fi
+fi 
 exit 0
 
