fix: Behebung von Bugs aus Review-Durchlauf (v1.24.0)
Behebt 37 verifizierte Fehler in den dc-Skripten. Highlights:

- dc-config: found-Flag vor die Node-Schleife -> App wird nicht mehr
  geloescht, wenn auf einem frueheren Node noch Container laufen
- dcd: dc data mount pruefen bevor rm; cd-Guard + Quoting
- dc: -a<app>-Parsing, docker-Exit-Code, ovw fetch/diff, data c/v,
  readme-exit, pull ueber alle Nodes, -i mehrstellige Indizes
- dc-backup: get_age gegen Datums-Suffixe robust; df -hP statt grep ^/
- dc-image: wget-Fehler pruefen, App validieren, rmup-Exit-Code
- dc-md-exec: getopt overwrite:, Split am ersten =, sed-Muster ankern
- dc-node: Header-Bedingung, DIR in image list config, Fehlermeldung
- dc-vserver: dc-${i}-Aufruf, node_type-Tippfehler
- dc-batch: delete loescht echtes Log-Dir; ok-Mail via $rc
- dc-swarm: docker service logs Reihenfolge
- diverse Tippfehler/Meldungen (dc-app, dc-hcloud, dc-manage, dc-yq,
  dc-inspect, dc-ls, dc-kvm, replace-helper)

VERSION 1.23.0 -> 1.24.0

diff --git a/bin/dc-image b/bin/dc-image
--- a/bin/dc-image
+++ b/bin/dc-image
@@ -51,7 +51,11 @@ if [ "$1" = "ls" ] ; then
   fi
   groups=$(dc-yq '.config.cluster.image_list.groups.[]')
   FI=$(mktemp)
-  wget -q -O $FI $url
+  if ! wget -q -O "$FI" "$url" || [ ! -s "$FI" ] ; then
+    echo "error: could not fetch image list from <$url>"
+    rm -f "$FI"
+    exit 1
+  fi
   update_list=""
   for g in $groups ; do
     update_list="$update_list "$(dc-yq '.'$g'.[]' $FI)
@@ -136,8 +140,12 @@ if [ "${1}" = "update" ] ; then
 
   yaml_file=$(dc-yq '.apps.'$app'.compose_yml')
   app_dir=$(dc-yq '.apps.'$app'.app_dir')
+  if [ "$app_dir" = "null" -o -z "$app_dir" -o "$yaml_file" = "null" -o -z "$yaml_file" ] ; then
+    echo "error: unknown app <$app>"
+    exit 1
+  fi
 
-  ( cd ${app_dir} ; dc docker pull ${image} )
+  ( cd "${app_dir}" || exit 1 ; dc docker pull ${image} )
   if [ "$?" != "0" ] ; then
     echo "error: downloading image <${image}>!!!"
     exit 1
@@ -151,7 +159,12 @@ if [ "${1}" = "update" ] ; then
        dc-yq -i '.services.'$s'.image = "'${image}'"' $yaml_file 
     fi
   done
-  ( cd ${app_dir} ; dc rmup )
+  ( cd "${app_dir}" || exit 1 ; dc rmup )
+  rc=$?
+  if [ "$rc" != "0" ] ; then
+    echo "error: redeploy (dc rmup) failed for app <${app}>!!!"
+  fi
+  exit $rc
 fi
 
 exit 0
diff --git a/bin/dc-node b/bin/dc-node
--- a/bin/dc-node
+++ b/bin/dc-node
@@ -186,7 +186,7 @@ dc mounts umount
 
 for HOST in $hlist ; do
   if [ "$CMD" = "cmd" ] ; then
-    if [ "$H" = "--all" ] ; then
+    if [ "$opt_type" != "" ] ; then
       echo "#"    
       echo "# ssh ${HOST} $*"
       echo "#"
@@ -374,6 +374,13 @@ if [ "$CMD" = "image"   ] ; then
         target="${url}/${cluster}_${node}_${rep}_${nam}"
         target=${target%:}
         if [ "$2" = "config" ] ; then
+          DIR=""
+          for a in $(dc-list apps -n $node) ; do
+            if dc-yq '.apps.'$a'.compose.services.*.image' ${MDE_DC_YAML} | grep -qx "$image" ; then
+              DIR=$(dc-yq '.apps.'$a'.app_dir' ${MDE_DC_YAML})
+              break
+            fi
+          done
           echo "$image;$DIR;${node}"
         else
           echo "############################################################"
@@ -397,7 +404,7 @@ if [ "$CMD" = "image"   ] ; then
           fi
           printf "${COL_GREEN}%s${COL_DEFAULT}\n" "dc -n ${node} docker image rm -f ${target}"
           dc -n  ${node} docker image rm -f     ${target}
-          if [ "$?" != "0" ] ; then echo "docker push error!!!" ; exit 1 ; fi
+          if [ "$?" != "0" ] ; then echo "docker image rm error!!!" ; exit 1 ; fi
         fi
         if [ "$cmd" = "restore" ] ; then
           dc -n  ${node} docker pull     ${target}
diff --git a/bin/dcd b/bin/dcd
--- a/bin/dcd
+++ b/bin/dcd
@@ -6,11 +6,14 @@ fi
 
 if [ "$1" = "pull" ] ; then
   HNAME=$(hostname)
-  dc data mount
+  if ! dc data mount ; then
+    echo "error: 'dc data mount' failed; aborting pull to avoid data loss" >&2
+    exit 1
+  fi
   rm -rvf ./dcd.${HNAME}
   list=$(cat dcd.list)
   for i in $list ; do
-    ( cd data ; rsync -Rav $i ../dcd.${HNAME})
+    ( cd data || exit 1 ; rsync -Rav "$i" "../dcd.${HNAME}" )
   done
   dc data umount
 fi
